"""
Kafka Producer — LLM Inference Events

Publishes inference events to the `llm.inference.events` topic
after every AI response generated by the DetectionBufferService.

Architecture role:
This is the data source for the entire analytics pipeline:

  DetectionBufferService generates response
            ↓
  KafkaProducerService.publish_inference_event()  ← this file
            ↓
  Kafka topic: llm.inference.events
            ↓
  Express Analytics (Node.js) consumer
            ↓
  MongoDB inference_logs collection
            ↓
  GraphQL gateway → Angular dashboard

Why fire-and-forget (async, non-blocking)?
The Flutter client is waiting for the detection response.
Publishing to Kafka must never slow down that response path.
I use asyncio to run the Kafka send in the background — the HTTP
response returns immediately, Kafka publish happens in parallel.

Why Kafka instead of direct HTTP to Express Analytics?
- Decoupling: the LLM Gateway has zero knowledge of the analytics service
- Resilience: if Express Analytics is down, events queue in Kafka
  and are consumed when it comes back — no data loss
- Replay: historical events can be reprocessed from any offset

Message schema matches the InferenceLog Mongoose model in Express Analytics:
{
    session_id:  str   — groups events from the same detection session
    timestamp:   str   — ISO 8601, set at publish time
    detections:  list  — YOLO results that triggered this inference
    llm: {
        runtime:      str   — gemini-2.5-flash | dart | go | cache | ollama
        cache_hit:    bool  — true = Redis LRU hit (~0.03ms), false = full call
        latency_ms:   float — end-to-end inference latency
        response:     str   — the generated AI message
        prompt_tokens: int  — only present for full LLM calls (not cache hits)
    }
    cache: {
        hit:         bool
        key_hash:    str   — the LRU cache key used for lookup
        miss_reason: str   — why cache missed (e.g. 'new_detection_pattern')
    }
}
"""

import asyncio
import json
import logging
import os
from datetime import datetime, timezone
from typing import Optional

from aiokafka import AIOKafkaProducer

logger = logging.getLogger(__name__)


class KafkaProducerService:
    """
    Async Kafka producer — wraps AIOKafkaProducer with lifecycle management.

    Designed as a singleton (one producer instance for the entire app lifetime).
    AIOKafkaProducer maintains an internal connection pool and batches messages
    automatically — instantiating per-request would be wasteful and slow.

    Lazy start: the producer connects on first use, not at import time.
    This prevents startup failures if Kafka isn't ready when the gateway boots.
    The docker-compose depends_on with service_healthy handles ordering,
    but lazy init adds a second layer of resilience for cold starts.
    """

    def __init__(self):
        self._producer: Optional[AIOKafkaProducer] = None
        self._brokers = os.getenv("KAFKA_BROKERS", "kafka:9092")
        self._topic   = os.getenv("KAFKA_TOPIC",   "llm.inference.events")
        self._started = False

    async def _ensure_started(self):
        """
        Lazily initialize and start the Kafka producer on first use.

        Why lazy?
        At container startup, Kafka may not be fully ready even after the
        healthcheck passes. Lazy init lets the first real request trigger
        the connection, by which point Kafka is reliably available.
        """
        if not self._started:
            self._producer = AIOKafkaProducer(
                bootstrap_servers=self._brokers,
                value_serializer=lambda v: json.dumps(v).encode("utf-8"),
                # Acks from leader only — balance durability vs latency
                # For production: acks="all" for full ISR acknowledgment
                acks=1,
            )
            await self._producer.start()
            self._started = True
            logger.info(f"✅ Kafka producer connected → {self._brokers}")

    async def publish_inference_event(
        self,
        session_id: str,
        detections: list,
        runtime: str,
        cache_hit: bool,
        latency_ms: float,
        response: str,
        cache_key_hash: str = "",
        miss_reason: str = "",
        prompt_tokens: Optional[int] = None,
    ) -> None:
        """
        Publish one inference event to the llm.inference.events topic.

        Called from the /buffer/add-detection endpoint after the buffer
        flushes and the DetectionBufferService returns an AI response.

        Parameters match the InferenceLog Mongoose schema in Express Analytics
        exactly — any change here must be mirrored there.

        Errors are caught and logged — a Kafka publish failure must never
        propagate back to the Flutter client waiting for its detection result.
        """
        await self._ensure_started()

        event = {
            "session_id":  session_id,
            "timestamp":   datetime.now(timezone.utc).isoformat(),
            "detections":  detections,
            "llm": {
                "runtime":      runtime,
                "cache_hit":    cache_hit,
                "latency_ms":   round(latency_ms, 2),
                "response":     response,
                # prompt_tokens only present for full LLM calls (not cache hits)
                **({"prompt_tokens": prompt_tokens} if prompt_tokens is not None else {}),
            },
            "cache": {
                "hit":         cache_hit,
                "key_hash":    cache_key_hash,
                "miss_reason": miss_reason if not cache_hit else "",
            },
        }

        try:
            await self._producer.send_and_wait(self._topic, event)
            logger.info(
                f"📤 Kafka event published | runtime: {runtime} "
                f"| cache_hit: {cache_hit} | latency: {latency_ms:.1f}ms"
            )
        except Exception as e:
            # Log and swallow — Kafka failure must not affect the detection response
            logger.error(f"❌ Kafka publish failed: {e}")

    async def stop(self):
        """
        Gracefully flush and close the producer.
        Called on FastAPI shutdown to ensure in-flight messages are sent
        before the process exits.
        """
        if self._started and self._producer:
            await self._producer.stop()
            logger.info("🛑 Kafka producer stopped")


# Module-level singleton — imported and used directly in main.py
kafka_producer = KafkaProducerService()
