"""add detection tables

Revision ID: 82449c996533
Revises: c49e82f2d940
Create Date: 2025-12-02 12:13:22.399577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82449c996533'
down_revision: Union[str, Sequence[str], None] = 'c49e82f2d940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='detectionstatus'), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_id'), 'detection_results', ['id'], unique=False)
    op.create_index(op.f('ix_detection_results_model_version'), 'detection_results', ['model_version'], unique=False)
    op.create_table('bounding_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detection_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounding_boxes_id'), 'bounding_boxes', ['id'], unique=False)
    op.create_index(op.f('ix_bounding_boxes_label'), 'bounding_boxes', ['label'], unique=False)
    op.create_table('detection_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('preprocessing_time_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_id')
    )
    op.create_index(op.f('ix_detection_metrics_id'), 'detection_metrics', ['id'], unique=False)
    op.drop_table('post')
    op.drop_index(op.f('flyway_schema_history_s_idx'), table_name='flyway_schema_history')
    op.drop_table('flyway_schema_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name=op.f('flyway_schema_history_pk'))
    )
    op.create_index(op.f('flyway_schema_history_s_idx'), 'flyway_schema_history', ['success'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('post_pkey'))
    )
    op.drop_index(op.f('ix_detection_metrics_id'), table_name='detection_metrics')
    op.drop_table('detection_metrics')
    op.drop_index(op.f('ix_bounding_boxes_label'), table_name='bounding_boxes')
    op.drop_index(op.f('ix_bounding_boxes_id'), table_name='bounding_boxes')
    op.drop_table('bounding_boxes')
    op.drop_index(op.f('ix_detection_results_model_version'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_id'), table_name='detection_results')
    op.drop_table('detection_results')
    # ### end Alembic commands ###
