package com.example.dashboard.post.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO for the Post response.
 * This is the object returned to the client after create/get a post.
 *
 * Include all the fields, including the ones generated by the server (id, author, createdAt).
 */
@Data                      // Generates @Getter, @Setter, @ToString, @EqualsAndHashCode
@Builder                   // Pattern Builder: PostResponseDTO.builder().title("...").build()
@NoArgsConstructor         // Constructor without args (needed for Jackson)
@AllArgsConstructor        // Constructor with all args (needed for @Builder)
public class PostResponseDTO {

    /**
     * ID generated by the database.
     * It is not coming in the request, is generated at saving.
     */
    private Long id;

    /**
     * Post title(coming from the client)
     */
    private String title;

    /**
     * Post content (coming from the client)
     */
    private String content;

    /**
     * Post autor (extracted from the JWT at the server)
     */
    private String author;

    /**
     * Creation Timestamp (generated by the server)
     */
    private LocalDateTime createdAt;
}