-- Open the pluggable database
ALTER PLUGGABLE DATABASE XEPDB1 OPEN;
ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE;

-- Create user/schema for your project
CREATE USER kus4n4g1 IDENTIFIED BY 2sE159077;
GRANT CONNECT, RESOURCE TO kus4n4g1;
ALTER USER kus4n4g1 QUOTA UNLIMITED ON USERS;

