package com.example.dashboard.post;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Entity representing a Post in the database.
 * This class maps directly to the "post" table.
 *
 * IMPORTANT: This class should NOT be exposed directly in the Controller.
 * Use DTOs (PostRequestDTO, PostResponseDTO) for the API.
 */
@Entity
@Table(name = "post") // Explicit table name (optional, defaults to class name)
@Getter                // Only @Getter on Entities (not @Data)
@Setter                // Only @Setter on Entities
@Builder               // Builder pattern
@NoArgsConstructor     // JPA requires this constructor
@AllArgsConstructor    // Required for @Builder
public class Post {

    /**
     * Unique ID of the post, automatically generated by the database.
     * IDENTITY strategy: PostgreSQL uses SERIAL or BIGSERIAL.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the post.
     * Maps to a VARCHAR(200) column.
     */
    @Column(name = "title", nullable = false, length = 200)
    private String title;

    /**
     * Content of the post.
     * Maps to a TEXT column (no size limit).
     */
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * User who created the post (username from JWT).
     * NOT a FK relationship for now (just a stored string).
     */
    @Column(name = "author", nullable = false)
    private String author;

    /**
     * Timestamp of when the post was created.
     * Automatically set when first persisted.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA hook executed BEFORE persisting (INSERT).
     * Automatically sets the timestamp.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}
